# Makefile generated by OpenModelica
# Platform: linux64

# Simulations use -O3 by default
CC=clang
CXX=clang++
LINK=clang -shared
EXEEXT=
DLLEXT=.so
CFLAGS_BASED_ON_INIT_FILE=
# define OMC_CFLAGS_OPTIMIZATION env variable to your desired optimization level to override this
OMC_CFLAGS_OPTIMIZATION=-Os
DEBUG_FLAGS=$(OMC_CFLAGS_OPTIMIZATION)
CFLAGS=$(CFLAGS_BASED_ON_INIT_FILE) $(DEBUG_FLAGS) -fPIC -falign-functions -mfpmath=sse -fno-dollars-in-identifiers ${MODELICAUSERCFLAGS}   
CPPFLAGS= -I"/usr/bin/../include/omc/c" -I. -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME -DOMC_MODEL_PREFIX=PVWindEES -DOMC_NUM_MIXED_SYSTEMS=0 -DOMC_NUM_LINEAR_SYSTEMS=0 -DOMC_NUM_NONLINEAR_SYSTEMS=0 -DOMC_NDELAY_EXPRESSIONS=0 -DOMC_NVAR_STRING=0
# define OMC_LDFLAGS_LINK_TYPE env variable to "static" to override this
OMC_LDFLAGS_LINK_TYPE=dynamic
RUNTIME_LIBS= -Wl,--no-as-needed -Wl,--disable-new-dtags -lSimulationRuntimeC -llapack -lblas -lm -lm -lomcgc -lpthread -rdynamic -Wl,--no-undefined
LDFLAGS=-L"/usr/bin/../lib/x86_64-linux-gnu/omc" -L"/usr/bin/../lib" -Wl,-rpath,"/usr/bin/../lib/x86_64-linux-gnu/omc" -Wl,-rpath,"/usr/bin/../lib"   $(RUNTIME_LIBS) 
DIREXTRA=-L"/media/yewang/Data/Work/Research/Topics/yewang/HILTCRC/repo/RenewableTherm"
MAINFILE=PVWindEES.c
MAINOBJ=PVWindEES.o
CFILES=PVWindEES_functions.c PVWindEES_records.c \
PVWindEES_01exo.c PVWindEES_02nls.c PVWindEES_03lsy.c PVWindEES_04set.c PVWindEES_05evt.c PVWindEES_06inz.c PVWindEES_07dly.c \
PVWindEES_08bnd.c PVWindEES_09alg.c PVWindEES_10asr.c PVWindEES_11mix.c PVWindEES_12jac.c PVWindEES_13opt.c PVWindEES_14lnz.c \
PVWindEES_15syn.c PVWindEES_16dae.c PVWindEES_17inl.c 

OFILES=$(CFILES:.c=.o)
GENERATEDFILES=$(MAINFILE) PVWindEES.makefile PVWindEES_literals.h PVWindEES_functions.h $(CFILES)

.PHONY: omc_main_target clean bundle

# This is to make sure that PVWindEES_*.c are always compiled.
.PHONY: $(CFILES)

omc_main_target: $(MAINOBJ) PVWindEES_functions.h PVWindEES_literals.h $(OFILES)
	$(CC) -I. -o PVWindEES$(EXEEXT) $(MAINOBJ) $(OFILES) $(CPPFLAGS) $(DIREXTRA)  "-L/usr/bin/../lib/x86_64-linux-gnu/omc" -Wl,-rpath="/usr/bin/../lib/x86_64-linux-gnu/omc" "-L/usr/bin/../lib/" -Wl,-rpath="/usr/bin/../lib/" "-L/home/yewang/.openmodelica/binaries/Modelica" -Wl,-rpath="/home/yewang/.openmodelica/binaries/Modelica" "-L/usr/lib/omlibrary/Modelica 3.2.3/Resources/Library/x86_64-linux" -Wl,-rpath="/usr/lib/omlibrary/Modelica 3.2.3/Resources/Library/x86_64-linux" "-L/usr/lib/omlibrary/Modelica 3.2.3/Resources/Library/linux64" -Wl,-rpath="/usr/lib/omlibrary/Modelica 3.2.3/Resources/Library/linux64" "-L/usr/lib/omlibrary/Modelica 3.2.3/Resources/Library" -Wl,-rpath="/usr/lib/omlibrary/Modelica 3.2.3/Resources/Library" -lModelicaExternalC -lModelicaStandardTables -lModelicaIO -lModelicaMatIO -lzlib $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)
clean:
	@rm -f PVWindEES_records.o $(MAINOBJ)

bundle:
	@tar -cvf PVWindEES_Files.tar $(GENERATEDFILES)