/* Additional record code for PVWindEES generated by the OpenModelica Compiler OpenModelica 1.17.0. */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "PVWindEES_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

